apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: another-app
  name: another-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-app
  template:
    metadata:
      labels:
        app: another-app
    spec:
      containers:
      - image: nginxdemos/hello
        name: echoserver